# Generated by Django 3.2.12 on 2023-04-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
    ]
