# Generated by Django 3.2.12 on 2023-04-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, upload_to='portada'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='visitas',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
