# Generated by Django 3.2.12 on 2023-04-19 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20230419_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Categoria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='libro.categoria'),
        ),
    ]
