# Generated by Django 3.2.12 on 2023-04-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_alter_libro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='visitas',
            field=models.PositiveIntegerField(),
        ),
    ]
